version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: symfony_track
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Europe/Moscow  # Продолжайте устанавливать TZ
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgdata:
